In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings

filterwarnings("ignore")
%matplotlib inline

In [24]:
df= pd.read_csv("data/data.csv")

In [25]:
df.shape

(200000, 16)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  object
 2   Campaign_Type     200000 non-null  object
 3   Target_Audience   200000 non-null  object
 4   Duration          200000 non-null  object
 5   Channel_Used      200000 non-null  object
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  object
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  object
 10  Language          200000 non-null  object
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  object
 15  Date              200000 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 24.4+ MB

In [27]:
df['Date'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d')
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Year,Month,Day
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01,2021,1,1
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02,2021,1,2
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03,2021,1,3
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04,2021,1,4
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05,2021,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,199996,TechCorp,Display,All Ages,30 days,Google Ads,0.06,"$18,365.00",2.84,Chicago,German,858,5988,1,Tech Enthusiasts,2021-12-07,2021,12,7
199996,199997,DataTech Solutions,Email,Men 25-34,15 days,Facebook,0.02,"$8,168.00",4.14,Chicago,Spanish,228,3068,7,Foodies,2021-12-08,2021,12,8
199997,199998,DataTech Solutions,Social Media,Men 18-24,45 days,Website,0.05,"$13,397.00",3.25,New York,Mandarin,723,9548,3,Tech Enthusiasts,2021-12-09,2021,12,9
199998,199999,Innovate Industries,Influencer,All Ages,30 days,YouTube,0.10,"$18,508.00",3.86,Houston,French,528,2763,1,Foodies,2021-12-10,2021,12,10
199999,200000,Innovate Industries,Social Media,Women 35-44,45 days,Google Ads,0.01,"$13,835.00",6.64,Chicago,Spanish,924,7287,8,Tech Enthusiasts,2021-12-11,2021,12,11

In [ ]:
list_cast_as_object = ['Campaign_ID']
for column in list_cast_as_object:
    df[column] = df[column].astype('object')

In [53]:
for column_name in df.columns:
    print(column_name, df[column_name].dtype, df[column_name].unique())

Campaign_ID object [1 2 3 ... 199998 199999 200000]
Company object ['Innovate Industries' 'NexGen Systems' 'Alpha Innovations'
 'DataTech Solutions' 'TechCorp']
Campaign_Type object ['Email' 'Influencer' 'Display' 'Search' 'Social Media']
Target_Audience object ['Men 18-24' 'Women 35-44' 'Men 25-34' 'All Ages' 'Women 25-34']
Duration object ['30 days' '60 days' '15 days' '45 days']
Channel_Used object ['Google Ads' 'YouTube' 'Instagram' 'Website' 'Facebook' 'Email']
Conversion_Rate float64 [0.04 0.12 0.07 0.11 0.05 0.13 0.08 0.09 0.14 0.02 0.06 0.01 0.03 0.1
 0.15]
Acquisition_Cost object ['$16,174.00' '$11,566.00' '$10,200.00' ... '$14,111.00' '$13,941.00'
 '$15,040.00']
ROI float64 [6.29 5.61 7.18 5.55 6.5  4.36 2.86 6.73 3.78 3.49 3.59 4.91 7.06 5.28
 2.91 4.53 4.48 6.08 3.83 7.99 6.21 2.12 7.31 6.03 6.23 3.29 7.12 3.61
 2.77 6.83 4.42 2.71 7.81 2.51 7.24 2.62 2.21 6.97 4.57 3.44 5.6  4.77
 3.31 6.8  7.4  3.8  5.25 3.98 5.79 6.48 7.62 3.35 6.15 3.7  6.66 2.7
 4.93 2.27 5.32 7.04 3.71 7.43 7.28 6.33 2.72 7.98 4.74 5.58 7.46 5.63
 6.67 2.03 3.23 4.82 7.74 6.57 3.74 3.99 2.3  7.38 2.22 7.89 4.41 2.01
 6.98 7.   2.57 7.19 4.61 3.69 7.96 3.12 4.86 4.54 6.87 7.17 2.17 7.32
 4.79 6.4  5.39 7.58 4.04 7.86 4.98 7.65 6.78 7.61 5.5  6.68 4.32 3.16
 6.63 6.65 7.54 2.41 6.46 3.56 4.9  6.17 3.77 3.43 3.48 5.86 4.72 5.13
 2.83 2.94 2.15 2.98 5.67 2.66 7.41 4.23 5.74 6.55 3.09 3.17 5.94 8.
 5.41 4.62 6.1  3.76 6.9  5.29 6.06 3.84 4.29 2.58 3.2  3.97 7.27 6.28
 7.8  5.46 2.46 5.64 4.7  4.28 3.62 3.72 4.37 2.63 4.22 5.83 7.51 7.49
 2.87 3.66 2.81 7.94 2.39 7.67 2.79 4.39 5.85 3.91 5.36 7.76 6.93 5.38
 5.08 2.89 4.26 7.47 5.12 3.13 5.99 5.75 4.24 5.66 3.02 5.23 2.05 6.53
 3.26 3.42 5.33 4.55 6.92 7.63 7.64 2.56 5.69 6.44 7.1  4.52 7.66 3.54
 3.39 4.65 7.25 7.56 3.05 5.2  5.48 6.62 3.9  3.01 7.68 7.08 4.47 5.88
 4.3  2.25 2.09 5.09 7.2  6.05 6.35 6.82 4.71 6.02 7.55 5.4  5.59 3.
 2.34 7.9  4.02 5.54 3.89 4.1  2.69 7.45 7.02 3.15 3.11 6.12 5.22 5.92
 2.28 5.27 4.99 4.14 3.92 7.34 2.59 4.16 4.25 5.82 6.59 7.77 4.13 4.63
 7.59 2.4  3.75 6.38 3.46 4.05 4.45 7.73 7.57 7.14 3.57 3.37 6.94 3.96
 2.18 4.27 4.75 3.53 6.74 2.97 6.26 4.06 4.46 2.6  6.47 2.92 7.69 4.87
 3.14 7.91 4.64 5.68 6.43 7.97 4.4  2.32 5.34 2.76 6.6  4.21 6.99 4.73
 5.06 5.7  4.88 2.55 2.64 7.39 7.13 5.1  4.69 4.09 5.87 4.19 5.72 5.81
 5.15 2.75 6.95 7.11 2.26 6.81 2.82 5.56 2.47 3.1  7.03 4.15 3.55 6.42
 7.85 2.35 5.04 6.07 3.22 5.8  7.42 2.5  3.58 7.07 7.92 3.85 5.97 4.97
 2.24 5.21 5.05 3.28 6.11 7.88 2.29 2.02 7.26 5.65 7.44 5.89 2.84 6.76
 5.76 5.45 5.03 7.05 6.2  7.83 5.47 2.43 3.87 6.01 6.7  6.45 7.84 5.01
 6.85 3.95 7.52 6.58 7.01 3.07 4.96 2.67 4.76 4.18 3.65 6.04 4.2  2.65
 4.56 7.53 7.75 6.77 4.84 5.3  7.09 2.13 5.73 3.63 2.06 3.27 6.61 7.21
 4.5  2.2  3.24 6.41 2.19 7.78 2.42 4.38 3.25 4.8  3.51 6.56 7.95 6.19
 6.72 2.54 2.78 3.52 6.86 4.12 6.34 3.19 7.29 7.87 6.36 7.36 2.33 6.88
 4.31 7.82 2.96 5.43 4.49 3.45 4.95 3.34 7.6  2.36 4.67 3.86 7.7  5.44
 5.52 2.8  6.51 5.07 4.51 2.08 2.38 3.79 5.57 5.26 3.67 2.04 5.51 5.17
 6.39 5.42 4.89 6.31 7.37 5.84 2.16 4.33 3.3  7.48 2.48 5.9  5.   4.01
 4.68 6.89 5.77 6.   6.71 3.47 4.08 4.17 2.99 6.24 7.71 5.93 3.06 4.78
 5.35 6.32 3.64 2.52 5.71 5.02 3.93 5.16 3.08 2.74 3.6  2.68 3.32 2.95
 6.79 3.41 4.43 5.24 4.85 5.49 5.18 2.   6.18 5.31 4.34 6.52 5.91 6.3
 2.88 4.07 3.03 6.96 6.64 4.44 2.07 7.22 6.22 2.93 2.31 6.25 5.14 5.11
 6.69 2.23 2.37 7.16 4.03 4.66 3.4  2.11 6.37 5.96 5.37 2.73 4.83 3.73
 4.   7.79 6.49 7.23 4.58 7.72 2.49 3.18 3.81 3.38 3.33 5.78 2.14 6.91
 6.13 3.5  7.3  5.53 6.54 3.88 2.45 3.94 4.35 4.81 4.11 6.16 3.68 7.93
 6.84 6.14 3.36 2.53 5.19 7.5  4.6  6.75 4.92 3.82 5.95 4.94 5.98 2.9
 3.21 2.1  6.09 6.27 2.44 2.61 4.59 3.04 7.35 5.62 7.15 2.85 7.33]
Location object ['Chicago' 'New York' 'Los Angeles' 'Miami' 'Houston']
Language object ['Spanish' 'German' 'French' 'Mandarin' 'English']
Clicks int64 [ 506  116  584  217  379  100  817  624  861  642  321  659  677  994
  482  299  931  218  182  193  975  319  646  764  527  809  953  604
  384  952  512  309  367  243  360  250  822  833  663  268  212  598
  988  282  992  903  629  190  150  134  657  385  537  450  178  164
  569  330  256  849  261  592  201  648  187  839  240  932  694  202
  416  576  300  776  492  763  791  737  159  913  238  635  597  550
  956  628  938  147  108  395  419  463  521  706  207  583  864  387
  560  306  740  115  366  552  369  886  447  595  438  652  802  841
  137  850  727  986  259  942  166  508  885  158  857  481  999  939
  666  359  328  571  845  585  418  208  556  734  643  165  693  404
  257  901  724  672  148  488  420  616  170  957  872  716  998  568
  421  797  668  303  540  801  436  683  862  944  241  200  883  690
  372  505  961  209  312  542  461  842  743  423  433  146  117  324
  317  472  896  132  210  280  308  554  868  376  264  773  726  614
  967  167  924  715  198  285  153  660  111  820  935  685  703  409
  662  320  587  119  970  993  350  897  162  949  154  735  341  222
  314  838  394  536  143  426  295  661  441  983  354  570  676  741
  274  860  397  449  831  631  921  262  294  704  399  664  784  697
  247  334  199  406  771  586  566  858  254  803  325  695  195  513
  645  439  458  233  515  730  619  946  326  800  517  130  602  474
  563  497  577  902  443  531  788  480  819  747  471  363  388  206
  995  453  978  639  699  647  171  290  710  679  969  636  318  846
  289  887  829  335  123  435  718  733  454  806  232  125  824  881
  378  834  709  696  239  890  412  118  525  609  649  908  578  140
  124  562  466  184  991  671  469  377  963  279  656  789  520  582
  221  331  316  301  987  917  856  933  104  794  610  816  176  228
  818  518  292  826  120  275  455  244  538  149  753  368  194  172
  580  798  940  637  736  305  870  702  767  701  893  467  374  260
  353  682  830  955  215  965  640  494  432  237  775  581  745  837
  265  941  403  905  761  457  430  973  129  698  588  141  655  557
  411  750  340  714  876  605  444  348  971  133  593  934  594  155
  213  392  607  530  177  145  626  667  425  722  434  866  574  954
  960  670  575  533  899  836  214  173  712  825  131  483  344  102
  307  496  964  174  373  345  205  754  304  322  302  464  912  448
  728  371  106  612  782  532  311  729  183  549  892  984  186  591
  211  618  507  945  400  678  427  269  398  477  351  504  381  621
  705  284  293  968  617  364  452  561  606  623  502  332  236  382
  891  599  630  266  287  675  389  717  760  424  721  252  719  192
  651  900  738  768  490  188  431  633  739  422  408  277  898  179
  863  689  600  407  774  227  181  297  708  375  446  189  191  990
  283  235  281  879  907  337  744  853  541  930  762  114  383  428
  390  249  976  152  713  465  144  278  347  919  547  534  545  204
  723  603  396  128  665  503  622  936  230  417  271  346  769  813
  270  805  327  795  686  522  989  323  808  342  495  234  487  272
  772  611  725  755  911  914  792  343  500  169  958  338  832  653
  756  273  558  814  468  596  405  786  895  981  644  962  748  691
  460  951  929  681  414  107  445  865  196  470  442  519  559  632
  229  783  224  608  263  473  997  101  796  493  937  823  972  163
  979  918  601  812  161  758  156  122  357  440  510  103  884  759
  757  349  573  985  216  688  777  869  906  790  851  415  105  157
  746  877  752  501  852  197  548  821  478  804  810  888  843  925
  315  867  590  514  927  811  219  391  579  203  429  151  613  654
  799  674  855  638  680  138  352  977  731  959  248  615  356  255
  565  847  339  393  785  904  380  180  479  185  498  779  329  687
  386  871  459  456  732  139  848  875  673  711  572  110  589  535
  451  313  526  854  778  707  544  950  231  873  310  567 1000  555
  258  401  551  251  878  827  700  553  889  276  909  749  226  160
  529  815  410  926  485  916  358  684  370  692  928  135  361  947
  807  915  499  168  225  489  658  669  920  288  484  523  650  996
  491  844  828  126  246  462  528  880  546  253  509  943  882  365
  136  543  245  720  142  780  840  286  751  948  974  298  787  923
  770  874  242  516  336  641  634  793  781  620  362  402  894  627
  113  625  355  524  109  267  980  437  223  127  476  112  742  859
  511  220  835  121  539  564  922  910  486  175  333  475  766  765
  413  966  982  291  296]
Impressions int64 [1922 7523 7698 ... 3538 1245 2504]
Engagement_Score int64 [ 6  7  1  3 10  4  5  9  2  8]
Customer_Segment object ['Health & Wellness' 'Fashionistas' 'Outdoor Adventurers' 'Foodies'
 'Tech Enthusiasts']
Date object ['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31' '2021-02-01' '2021-02-02' '2021-02-03' '2021-02-04'
 '2021-02-05' '2021-02-06' '2021-02-07' '2021-02-08' '2021-02-09'
 '2021-02-10' '2021-02-11' '2021-02-12' '2021-02-13' '2021-02-14'
 '2021-02-15' '2021-02-16' '2021-02-17' '2021-02-18' '2021-02-19'
 '2021-02-20' '2021-02-21' '2021-02-22' '2021-02-23' '2021-02-24'
 '2021-02-25' '2021-02-26' '2021-02-27' '2021-02-28' '2021-03-01'
 '2021-03-02' '2021-03-03' '2021-03-04' '2021-03-05' '2021-03-06'
 '2021-03-07' '2021-03-08' '2021-03-09' '2021-03-10' '2021-03-11'
 '2021-03-12' '2021-03-13' '2021-03-14' '2021-03-15' '2021-03-16'
 '2021-03-17' '2021-03-18' '2021-03-19' '2021-03-20' '2021-03-21'
 '2021-03-22' '2021-03-23' '2021-03-24' '2021-03-25' '2021-03-26'
 '2021-03-27' '2021-03-28' '2021-03-29' '2021-03-30' '2021-03-31'
 '2021-04-01' '2021-04-02' '2021-04-03' '2021-04-04' '2021-04-05'
 '2021-04-06' '2021-04-07' '2021-04-08' '2021-04-09' '2021-04-10'
 '2021-04-11' '2021-04-12' '2021-04-13' '2021-04-14' '2021-04-15'
 '2021-04-16' '2021-04-17' '2021-04-18' '2021-04-19' '2021-04-20'
 '2021-04-21' '2021-04-22' '2021-04-23' '2021-04-24' '2021-04-25'
 '2021-04-26' '2021-04-27' '2021-04-28' '2021-04-29' '2021-04-30'
 '2021-05-01' '2021-05-02' '2021-05-03' '2021-05-04' '2021-05-05'
 '2021-05-06' '2021-05-07' '2021-05-08' '2021-05-09' '2021-05-10'
 '2021-05-11' '2021-05-12' '2021-05-13' '2021-05-14' '2021-05-15'
 '2021-05-16' '2021-05-17' '2021-05-18' '2021-05-19' '2021-05-20'
 '2021-05-21' '2021-05-22' '2021-05-23' '2021-05-24' '2021-05-25'
 '2021-05-26' '2021-05-27' '2021-05-28' '2021-05-29' '2021-05-30'
 '2021-05-31' '2021-06-01' '2021-06-02' '2021-06-03' '2021-06-04'
 '2021-06-05' '2021-06-06' '2021-06-07' '2021-06-08' '2021-06-09'
 '2021-06-10' '2021-06-11' '2021-06-12' '2021-06-13' '2021-06-14'
 '2021-06-15' '2021-06-16' '2021-06-17' '2021-06-18' '2021-06-19'
 '2021-06-20' '2021-06-21' '2021-06-22' '2021-06-23' '2021-06-24'
 '2021-06-25' '2021-06-26' '2021-06-27' '2021-06-28' '2021-06-29'
 '2021-06-30' '2021-07-01' '2021-07-02' '2021-07-03' '2021-07-04'
 '2021-07-05' '2021-07-06' '2021-07-07' '2021-07-08' '2021-07-09'
 '2021-07-10' '2021-07-11' '2021-07-12' '2021-07-13' '2021-07-14'
 '2021-07-15' '2021-07-16' '2021-07-17' '2021-07-18' '2021-07-19'
 '2021-07-20' '2021-07-21' '2021-07-22' '2021-07-23' '2021-07-24'
 '2021-07-25' '2021-07-26' '2021-07-27' '2021-07-28' '2021-07-29'
 '2021-07-30' '2021-07-31' '2021-08-01' '2021-08-02' '2021-08-03'
 '2021-08-04' '2021-08-05' '2021-08-06' '2021-08-07' '2021-08-08'
 '2021-08-09' '2021-08-10' '2021-08-11' '2021-08-12' '2021-08-13'
 '2021-08-14' '2021-08-15' '2021-08-16' '2021-08-17' '2021-08-18'
 '2021-08-19' '2021-08-20' '2021-08-21' '2021-08-22' '2021-08-23'
 '2021-08-24' '2021-08-25' '2021-08-26' '2021-08-27' '2021-08-28'
 '2021-08-29' '2021-08-30' '2021-08-31' '2021-09-01' '2021-09-02'
 '2021-09-03' '2021-09-04' '2021-09-05' '2021-09-06' '2021-09-07'
 '2021-09-08' '2021-09-09' '2021-09-10' '2021-09-11' '2021-09-12'
 '2021-09-13' '2021-09-14' '2021-09-15' '2021-09-16' '2021-09-17'
 '2021-09-18' '2021-09-19' '2021-09-20' '2021-09-21' '2021-09-22'
 '2021-09-23' '2021-09-24' '2021-09-25' '2021-09-26' '2021-09-27'
 '2021-09-28' '2021-09-29' '2021-09-30' '2021-10-01' '2021-10-02'
 '2021-10-03' '2021-10-04' '2021-10-05' '2021-10-06' '2021-10-07'
 '2021-10-08' '2021-10-09' '2021-10-10' '2021-10-11' '2021-10-12'
 '2021-10-13' '2021-10-14' '2021-10-15' '2021-10-16' '2021-10-17'
 '2021-10-18' '2021-10-19' '2021-10-20' '2021-10-21' '2021-10-22'
 '2021-10-23' '2021-10-24' '2021-10-25' '2021-10-26' '2021-10-27'
 '2021-10-28' '2021-10-29' '2021-10-30' '2021-10-31' '2021-11-01'
 '2021-11-02' '2021-11-03' '2021-11-04' '2021-11-05' '2021-11-06'
 '2021-11-07' '2021-11-08' '2021-11-09' '2021-11-10' '2021-11-11'
 '2021-11-12' '2021-11-13' '2021-11-14' '2021-11-15' '2021-11-16'
 '2021-11-17' '2021-11-18' '2021-11-19' '2021-11-20' '2021-11-21'
 '2021-11-22' '2021-11-23' '2021-11-24' '2021-11-25' '2021-11-26'
 '2021-11-27' '2021-11-28' '2021-11-29' '2021-11-30' '2021-12-01'
 '2021-12-02' '2021-12-03' '2021-12-04' '2021-12-05' '2021-12-06'
 '2021-12-07' '2021-12-08' '2021-12-09' '2021-12-10' '2021-12-11'
 '2021-12-12' '2021-12-13' '2021-12-14' '2021-12-15' '2021-12-16'
 '2021-12-17' '2021-12-18' '2021-12-19' '2021-12-20' '2021-12-21'
 '2021-12-22' '2021-12-23' '2021-12-24' '2021-12-25' '2021-12-26'
 '2021-12-27' '2021-12-28' '2021-12-29' '2021-12-30' '2021-12-31']

In [54]:
# df['Acquisition_Cost'] = df['Acquisition_Cost'].str.replace('$','').str.replace(',','').astype(float)
# df['Duration'] = df['Duration'].str.replace(' days', '').astype(int)

In [55]:
list_categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
list_numerical_columns = df.select_dtypes(include=['float64, int64']).columns.tolist()

In [56]:
df.sample(5)

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
106412,106413,Alpha Innovations,Search,Men 18-24,15 days,YouTube,0.10,"$9,801.00",2.21,Miami,French,234,1930,8,Fashionistas,2021-07-17
61916,61917,Innovate Industries,Social Media,Women 25-34,15 days,Email,0.02,"$8,124.00",5.10,Los Angeles,German,848,6903,7,Outdoor Adventurers,2021-08-20
86389,86390,Alpha Innovations,Display,All Ages,60 days,Email,0.13,"$14,071.00",5.68,Miami,German,761,1511,3,Fashionistas,2021-09-07
69772,69773,Innovate Industries,Search,Men 18-24,30 days,Facebook,0.04,"$7,921.00",2.32,Miami,Spanish,290,2222,2,Fashionistas,2021-02-27
127122,127123,TechCorp,Email,Men 18-24,15 days,Google Ads,0.14,"$17,578.00",4.03,Chicago,Spanish,384,2328,8,Tech Enthusiasts,2021-04-13