In [11]:
# ▶ pd.set option
import json
import numpy as np
import pandas as pd 
pd.set_option('display.max_columns',100)
pd.set_option('display.max_rows',100)  

# ▶ Data read
df = pd.read_csv("../../Case_study_20/data/data.csv")
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [13]:
df_sensor = df.drop(['TWF', 'HDF', 'PWF', 'OSF', 'RNF'], axis=1)
df_mode = df[['UDI','TWF','HDF','PWF','OSF','RNF']]

In [14]:
df = pd.merge(df_sensor, df_mode, how='left')
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [16]:
### Null values
print(df.isnull().sum())

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [17]:
df_null = pd.DataFrame(df.isnull().sum(), columns=['null'])
df_null['null_ratio'] = df_null['null'] /len(df)
df_null.sort_values(by=['null_ratio'], ascending=False)

                         null  null_ratio
UDI                         0         0.0
Product ID                  0         0.0
Type                        0         0.0
Air temperature [K]         0         0.0
Process temperature [K]     0         0.0
Rotational speed [rpm]      0         0.0
Torque [Nm]                 0         0.0
Tool wear [min]             0         0.0
Machine failure             0         0.0
TWF                         0         0.0
HDF                         0         0.0
PWF                         0         0.0
OSF                         0         0.0
RNF                         0         0.0

In [19]:
df.duplicated().value_counts()

False    10000
Name: count, dtype: int64

In [25]:
list_of_df = []

for i in df.columns:
    loof_df = pd.DataFrame({'val' : [i],
                            'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
    list_of_df.append(loof_df)
    
df_merge = pd.concat(list_of_df).reset_index(drop=True) # Concat하게 되면 list형태로 만들어졌던 list_of_df가 DataFrame으로 변환됨
df_merge['zero_ratio'] = df_merge['zero_cnt'] /len(df)
df_merge.sort_values(by=['zero_ratio'], ascending=False)

C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
C:\Users\TaeyoonKim\AppData\Local\Temp\ipykernel_27996\3960251026.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  'zero_cnt' : df[df[i] == 0].count()[0]}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0

                        val  zero_cnt  zero_ratio
13                      RNF      9981      0.9981
9                       TWF      9954      0.9954
11                      PWF      9905      0.9905
12                      OSF      9902      0.9902
10                      HDF      9885      0.9885
8           Machine failure      9661      0.9661
7           Tool wear [min]       120      0.0120
0                       UDI         0      0.0000
1                Product ID         0      0.0000
2                      Type         0      0.0000
3       Air temperature [K]         0      0.0000
4   Process temperature [K]         0      0.0000
5    Rotational speed [rpm]         0      0.0000
6               Torque [Nm]         0      0.0000

In [ ]:
df.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

### ***Numerical_list and Categorical_list***

In [28]:
numerical_list = []
categorical_list = []

for i in df.columns:
    if df[i].dtype == 'O':
        categorical_list.append(i)
    else:
        numerical_list.append(i)

print("Numerical_list:", numerical_list)
print("Categorical_list:", categorical_list)

Numerical_list: ['UDI', 'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']
Categorical_list: ['Product ID', 'Type']

In [29]:
for i in numerical_list:
    print(i, ":", df[i].nunique())

UDI : 10000
Air temperature [K] : 93
Process temperature [K] : 82
Rotational speed [rpm] : 941
Torque [Nm] : 577
Tool wear [min] : 246
Machine failure : 2
TWF : 2
HDF : 2
PWF : 2
OSF : 2
RNF : 2

In [30]:
list_of_df = []

for i in numerical_list:
    loof_df = pd.DataFrame({'val' : [i],
                            'nunique' : df[i].nunique()}) # 모두 같은 값이 나오기 때문에 count()이후에 인덱싱 0
    list_of_df.append(loof_df)
    
df_merge = pd.concat(list_of_df).reset_index(drop=True) # Concat하게 되면 list형태로 만들어졌던 list_of_df가 DataFrame으로 변환됨
df_merge.sort_values(by=['nunique'], ascending=False)

                        val  nunique
0                       UDI    10000
3    Rotational speed [rpm]      941
4               Torque [Nm]      577
5           Tool wear [min]      246
1       Air temperature [K]       93
2   Process temperature [K]       82
6           Machine failure        2
7                       TWF        2
8                       HDF        2
9                       PWF        2
10                      OSF        2
11                      RNF        2

In [32]:
print('Type:', df['Type'].nunique())

Type: 3